#!/bin/bash

gfortran -o hardroc.x physical_constants.f03 channel_char.f03 control.f03 lenfile.f03 factorial.f03 geometry_fun.f03 wigner3j.f03 input_routines.f03 calc_geometry.f03 icd_calc.f03 hardroc.f03
